# Generated by Django 3.1.1 on 2020-10-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deskreservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('to_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskreservation.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAreaNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskreservation.officearea')),
            ],
        ),
    ]
